## Data Importing and Cleaning

In [7]:
import pandas as pd

# Creating an artificial dataset
data = {
    'OrderID': [101, 102, 103, 103, 104],
    'Customer': ['Alice', 'Bob', 'Charlie', 'Charlie', 'Eve'],
    'Amount': [250, 300, None, None, 400],
    'Date': ['2023/01/15', '2023-01-16', '2023-01-16', '2023-01-16', '2023/01/17']
}

# Converting it to a DataFrame
df = pd.DataFrame(data)

# Display the raw data
print("Original Data:")
print(df)

Original Data:
   OrderID Customer  Amount        Date
0      101    Alice   250.0  2023/01/15
1      102      Bob   300.0  2023-01-16
2      103  Charlie     NaN  2023-01-16
3      103  Charlie     NaN  2023-01-16
4      104      Eve   400.0  2023/01/17


In [8]:
# Remove duplicate rows
df = df.drop_duplicates()

print("\nAfter Removing Duplicates:")
print(df)


After Removing Duplicates:
   OrderID Customer  Amount        Date
0      101    Alice   250.0  2023/01/15
1      102      Bob   300.0  2023-01-16
2      103  Charlie     NaN  2023-01-16
4      104      Eve   400.0  2023/01/17


In [9]:
# Remove rows where 'Amount' is less than zero
df = df[df['Amount'] >= 0]

print("\nAfter Removing Out-of-Range Values:")
print(df)


After Removing Out-of-Range Values:
   OrderID Customer  Amount        Date
0      101    Alice   250.0  2023/01/15
1      102      Bob   300.0  2023-01-16
4      104      Eve   400.0  2023/01/17


## Handling Missing Data

In [13]:
# Creating an artificial dataset with missing values
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [25, np.nan, 30, np.nan, 40],
    'Salary': [50000, 60000, np.nan, 40000, 70000],
    'City': ['New York', np.nan, 'Los Angeles', 'Chicago', 'New York']
}

df = pd.DataFrame(data)

# Display the dataset
print("Original Dataset:")
print(df)

Original Dataset:
      Name   Age   Salary         City
0    Alice  25.0  50000.0     New York
1      Bob   NaN  60000.0          NaN
2  Charlie  30.0      NaN  Los Angeles
3    David   NaN  40000.0      Chicago
4      Eve  40.0  70000.0     New York


In [14]:
# Check for missing values in each column
print("\nMissing Values in Each Column:")
print(df.isnull().sum())


Missing Values in Each Column:
Name      0
Age       2
Salary    1
City      1
dtype: int64


In [12]:
# Drop rows with missing values
df_dropped_rows = df.dropna()

# Drop columns with missing values
df_dropped_cols = df.dropna(axis=1)

print("\nDataset After Dropping Rows with Missing Values:")
print(df_dropped_rows)

print("\nDataset After Dropping Columns with Missing Values:")
print(df_dropped_cols)


Dataset After Dropping Rows with Missing Values:
    Name   Age   Salary      City
0  Alice  25.0  50000.0  New York
4    Eve  40.0  70000.0  New York

Dataset After Dropping Columns with Missing Values:
      Name
0    Alice
1      Bob
2  Charlie
3    David
4      Eve


In [15]:
# Fill missing values in 'City' with 'Unknown'
df['City'] = df['City'].fillna('Unknown')

print("\nAfter Filling Missing 'City' Values:")
print(df)


After Filling Missing 'City' Values:
      Name   Age   Salary         City
0    Alice  25.0  50000.0     New York
1      Bob   NaN  60000.0      Unknown
2  Charlie  30.0      NaN  Los Angeles
3    David   NaN  40000.0      Chicago
4      Eve  40.0  70000.0     New York


In [16]:
# Fill missing values in 'Age' with the mean
df['Age'] = df['Age'].fillna(df['Age'].mean())

# Fill missing values in 'Salary' with the median
df['Salary'] = df['Salary'].fillna(df['Salary'].median())

print("\nAfter Filling Missing 'Age' and 'Salary' Values:")
print(df)


After Filling Missing 'Age' and 'Salary' Values:
      Name        Age   Salary         City
0    Alice  25.000000  50000.0     New York
1      Bob  31.666667  60000.0      Unknown
2  Charlie  30.000000  55000.0  Los Angeles
3    David  31.666667  40000.0      Chicago
4      Eve  40.000000  70000.0     New York


In [17]:
# Interpolate missing values linearly
df['Age'] = df['Age'].interpolate()

print("\nAfter Interpolating 'Age':")
print(df)


After Interpolating 'Age':
      Name        Age   Salary         City
0    Alice  25.000000  50000.0     New York
1      Bob  31.666667  60000.0      Unknown
2  Charlie  30.000000  55000.0  Los Angeles
3    David  31.666667  40000.0      Chicago
4      Eve  40.000000  70000.0     New York


## Data Transformation

In [18]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler

# Creating an artificial dataset
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Math_Score': [50, 80, 70, 60, 90],
    'Science_Score': [30, 85, 75, 95, 40]
}

df = pd.DataFrame(data)

print("Original Dataset:")
print(df)

Original Dataset:
      Name  Math_Score  Science_Score
0    Alice          50             30
1      Bob          80             85
2  Charlie          70             75
3    David          60             95
4      Eve          90             40


In [19]:
scaler = MinMaxScaler()

# Apply normalization
df[['Math_Score', 'Science_Score']] = scaler.fit_transform(df[['Math_Score', 'Science_Score']])

print("\nAfter Normalization:")
print(df)


After Normalization:
      Name  Math_Score  Science_Score
0    Alice        0.00       0.000000
1      Bob        0.75       0.846154
2  Charlie        0.50       0.692308
3    David        0.25       1.000000
4      Eve        1.00       0.153846


In [20]:
scaler = StandardScaler()

# Apply standardization
df[['Math_Score', 'Science_Score']] = scaler.fit_transform(df[['Math_Score', 'Science_Score']])

print("\nAfter Standardization:")
print(df)


After Standardization:
      Name  Math_Score  Science_Score
0    Alice   -1.414214      -1.372813
1      Bob    0.707107       0.784465
2  Charlie    0.000000       0.392232
3    David   -0.707107       1.176697
4      Eve    1.414214      -0.980581


In [21]:
import numpy as np

# Creating a NumPy array
array = np.arange(1, 13).reshape(4, 3)
print("\nOriginal Array:")
print(array)

# Reshape to a different dimension
reshaped_array = array.reshape(2, 6)
print("\nReshaped Array:")
print(reshaped_array)


Original Array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Reshaped Array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [22]:
# Creating a dataset with categorical data
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'], 'City': ['NY', 'LA', 'NY', 'Chicago', 'LA']}

df = pd.DataFrame(data)

# Apply one-hot encoding
df_encoded = pd.get_dummies(df, columns=['City'])

print("\nAfter One-Hot Encoding:")
print(df_encoded)


After One-Hot Encoding:
      Name  City_Chicago  City_LA  City_NY
0    Alice         False    False     True
1      Bob         False     True    False
2  Charlie         False    False     True
3    David          True    False    False
4      Eve         False     True    False


In [23]:
import pandas as pd

# Creating an artificial dataset
data = {
    'Product': ['Laptop', 'Smartphone', 'Tablet', 'Monitor', 'Keyboard'],
    'Price': [1000, 800, 300, 200, 50],
    'Units_Sold': [50, 120, 70, 30, 200]
}

df = pd.DataFrame(data)

# Access the first two rows and first two columns
subset = df.iloc[:2, :2]

print("Subset Using iloc:")
print(subset)

Subset Using iloc:
      Product  Price
0      Laptop   1000
1  Smartphone    800


In [24]:
# Access rows by index label and specific columns
subset = df.loc[0:2, ['Product', 'Price']]

print("\nSubset Using loc:")
print(subset)


Subset Using loc:
      Product  Price
0      Laptop   1000
1  Smartphone    800
2      Tablet    300


In [25]:
# Filter products with a price greater than $300
filtered_df = df[df['Price'] > 300]

print("\nFiltered Data (Price > 300):")
print(filtered_df)


Filtered Data (Price > 300):
      Product  Price  Units_Sold
0      Laptop   1000          50
1  Smartphone    800         120


In [26]:
# Filter products priced above $300 and with more than 50 units sold
filtered_df = df[(df['Price'] > 300) & (df['Units_Sold'] > 50)]

print("\nFiltered Data (Price > 300 and Units Sold > 50):")
print(filtered_df)


Filtered Data (Price > 300 and Units Sold > 50):
      Product  Price  Units_Sold
1  Smartphone    800         120


In [27]:
# Fancy indexing with arrays
rows = [0, 2]  # First and third rows
columns = ['Price', 'Units_Sold']  # Specific columns
subset = df.loc[rows, columns]

print("\nSubset Using Fancy Indexing:")
print(subset)


Subset Using Fancy Indexing:
   Price  Units_Sold
0   1000          50
2    300          70


In [28]:
# Slicing rows 1 to 3 (exclusive) and all columns
subset = df.iloc[1:4, :]

print("\nSliced Data (Rows 1 to 3):")
print(subset)


Sliced Data (Rows 1 to 3):
      Product  Price  Units_Sold
1  Smartphone    800         120
2      Tablet    300          70
3     Monitor    200          30


In [29]:
# Filter rows where 'Product' contains 'phone'
filtered_df = df[df['Product'].str.contains('phone', case=False)]

print("\nFiltered Data (Product Contains 'phone'):")
print(filtered_df)


Filtered Data (Product Contains 'phone'):
      Product  Price  Units_Sold
1  Smartphone    800         120


## Concatenating and Transforming Datasets

In [30]:
import pandas as pd

# Creating two datasets
data1 = {
    'CustomerID': [1, 2, 3],
    'Name': ['Alice', 'Bob', 'Charlie']
}
data2 = {
    'CustomerID': [4, 5],
    'Name': ['David', 'Eve']
}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

# Concatenating datasets row-wise
combined_df = pd.concat([df1, df2], ignore_index=True)

print("Row-wise Concatenated Dataset:")
print(combined_df)

Row-wise Concatenated Dataset:
   CustomerID     Name
0           1    Alice
1           2      Bob
2           3  Charlie
3           4    David
4           5      Eve


In [31]:
# Creating datasets
data1 = {
    'CustomerID': [1, 2, 3],
    'Name': ['Alice', 'Bob', 'Charlie']
}
data2 = {
    'Purchase_Amount': [100, 200, 150]
}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

# Concatenating datasets column-wise
combined_df = pd.concat([df1, df2], axis=1)

print("\nColumn-wise Concatenated Dataset:")
print(combined_df)


Column-wise Concatenated Dataset:
   CustomerID     Name  Purchase_Amount
0           1    Alice              100
1           2      Bob              200
2           3  Charlie              150


In [32]:
# Dropping a column
df = combined_df.drop(columns=['Name'])

print("\nDataset After Dropping Column 'Name':")
print(df)


Dataset After Dropping Column 'Name':
   CustomerID  Purchase_Amount
0           1              100
1           2              200
2           3              150


In [34]:
# Adding a new column for purchase categories
df['Category'] = ['Low', 'High', 'Medium']

print("\nDataset After Adding a New Column:")
print(df)


Dataset After Adding a New Column:
   CustomerID  Purchase_Amount Category
0           1              100      Low
1           2              200     High
2           3              150   Medium


In [35]:
# Sorting by purchase amount in descending order
sorted_df = df.sort_values(by='Purchase_Amount', ascending=False)

print("\nSorted Dataset:")
print(sorted_df)


Sorted Dataset:
   CustomerID  Purchase_Amount Category
1           2              200     High
2           3              150   Medium
0           1              100      Low


In [36]:
# Creating a dataset for reshaping
data = {
    'CustomerID': [1, 1, 2, 2],
    'PurchaseType': ['Online', 'In-Store', 'Online', 'In-Store'],
    'Amount': [50, 50, 100, 100]
}

df = pd.DataFrame(data)

# Pivoting data to create a summary table
pivoted_df = df.pivot(index='CustomerID', columns='PurchaseType', values='Amount')

print("\nPivoted Dataset:")
print(pivoted_df)


Pivoted Dataset:
PurchaseType  In-Store  Online
CustomerID                    
1                   50      50
2                  100     100


In [37]:
# Adding duplicate rows for demonstration
df1 = pd.DataFrame({'CustomerID': [1, 2], 'Amount': [100, 200]})
df2 = pd.DataFrame({'CustomerID': [2, 3], 'Amount': [200, 150]})

# Row-wise concatenation
combined_df = pd.concat([df1, df2], ignore_index=True)

# Removing duplicates
cleaned_df = combined_df.drop_duplicates()

print("\nCleaned Dataset After Removing Duplicates:")
print(cleaned_df)


Cleaned Dataset After Removing Duplicates:
   CustomerID  Amount
0           1     100
1           2     200
3           3     150


## Logging and Data Backup

In [38]:
# Creating a sample dataset
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Los Angeles', 'Chicago']
}

df = pd.DataFrame(data)

# Log metadata
print("Dataset Information:")
print(df.info())

print("\nStatistical Summary:")
print(df.describe(include='all'))

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    3 non-null      object
 1   Age     3 non-null      int64 
 2   City    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes
None

Statistical Summary:
         Name   Age      City
count       3   3.0         3
unique      3   NaN         3
top     Alice   NaN  New York
freq        1   NaN         1
mean      NaN  30.0       NaN
std       NaN   5.0       NaN
min       NaN  25.0       NaN
25%       NaN  27.5       NaN
50%       NaN  30.0       NaN
75%       NaN  32.5       NaN
max       NaN  35.0       NaN


In [39]:
# Save metadata to a log file
with open("data_log.txt", "w") as log_file:
    df.info(buf=log_file)
    log_file.write("\n")
    log_file.write(str(df.describe(include='all')))

In [40]:
# Save a backup of the dataset
backup_path = "data_backup.csv"
df.to_csv(backup_path, index=False)

print("\nBackup created at:", backup_path)


Backup created at: data_backup.csv


## Practical Applications and Examples

In [42]:
import pandas as pd

# Load the dataset
mtcars_df = pd.read_csv(R'..\data\mtcars.csv')

# Display the first few rows of the dataset
mtcars_df.head()

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [43]:
# Filter cars with mpg > 25
high_mpg_cars = mtcars_df[mtcars_df['mpg'] > 25]

print("Cars with MPG > 25:")
print(high_mpg_cars[['Unnamed: 0', 'mpg']])

Cars with MPG > 25:
        Unnamed: 0   mpg
17        Fiat 128  32.4
18     Honda Civic  30.4
19  Toyota Corolla  33.9
25       Fiat X1-9  27.3
26   Porsche 914-2  26.0
27    Lotus Europa  30.4


In [44]:
# Creating a car prices dataset
prices_data = {
    'Unnamed: 0': ['Mazda RX4', 'Datsun 710', 'Toyota Corolla'],
    'Price': [15000, 12000, 18000]
}

prices_df = pd.DataFrame(prices_data)

# Merging the mtcars dataset with the prices dataset
merged_df = pd.merge(mtcars_df, prices_df, on='Unnamed: 0', how='left')

print("Merged Dataset:")
print(merged_df[['Unnamed: 0', 'mpg', 'Price']].head())

Merged Dataset:
          Unnamed: 0   mpg    Price
0          Mazda RX4  21.0  15000.0
1      Mazda RX4 Wag  21.0      NaN
2         Datsun 710  22.8  12000.0
3     Hornet 4 Drive  21.4      NaN
4  Hornet Sportabout  18.7      NaN


In [45]:
# Add a power-to-weight ratio column
mtcars_df['power_to_weight_ratio'] = mtcars_df['hp'] / mtcars_df['wt']

print("Dataset with New Feature (Power-to-Weight Ratio):")
print(mtcars_df[['Unnamed: 0', 'hp', 'wt', 'power_to_weight_ratio']].head())

Dataset with New Feature (Power-to-Weight Ratio):
          Unnamed: 0   hp     wt  power_to_weight_ratio
0          Mazda RX4  110  2.620              41.984733
1      Mazda RX4 Wag  110  2.875              38.260870
2         Datsun 710   93  2.320              40.086207
3     Hornet 4 Drive  110  3.215              34.214619
4  Hornet Sportabout  175  3.440              50.872093


In [46]:
# Group cars by the number of cylinders and calculate average mpg
avg_mpg_by_cyl = mtcars_df.groupby('cyl')['mpg'].mean().reset_index()

print("Average MPG by Number of Cylinders:")
print(avg_mpg_by_cyl)

Average MPG by Number of Cylinders:
   cyl        mpg
0    4  26.663636
1    6  19.742857
2    8  15.100000
